# mise.toml
[tools]
terraform = "1"
aws-cli = "2"
gcloud = "latest"

[env]
_.file = '.env'

[tasks.env]
description = "Run env to check environment variables"
run = "env"

[tasks.tf-init]
description = "Initialize terraform configuration"
run = "cd terraform && terraform init"

[tasks.tf-reconfigure]
description = "Reconfigure terraform backend"
run = "cd terraform && terraform init -reconfigure"

[tasks.tf-upgrade]
description = "Upgrade terraform providers"
run = "cd terraform && terraform init -upgrade"

[tasks.plan]
description = "Run terraform plan with configured workspace"
run = "cd terraform && terraform plan"

[tasks.validate]
description = "Validate terraform configuration"
run = "cd terraform && terraform validate"

[tasks.deploy]
description = "Deploy infrastructure after validation"
depends = ["validate", "plan"]
run = "cd terraform && terraform apply -auto-approve"

[tasks.tf-destroy]
description = "Destroy terraform managed infrastructure"
run = "cd terraform && terraform destroy"


[tasks.claude]
description = "Start Claude Code"
run = "claude"

[tasks.slackbot-clean]
description = "Clean Slack bot build directory"
run = "rm -r slackbot/build"

[tasks.slackbot-build-binary]
description = "Build Slack bot Go binary"
depends = ["slackbot-clean", "slackbot-test"]
run = "cd slackbot && mkdir -p build && CGO_ENABLED=0 GOOS=linux go build -a -ldflags '-extldflags \"-static\"' -o build/main ."

[tasks.slackbot-build]
description = "Build Slack bot container image"
depends = ["slackbot-build-binary"]
run = "docker build -t slackbot ./slackbot"

[tasks.slackbot-test]
description = "Run Slack bot tests"
run = "cd slackbot && go test -v"

[tasks.slackbot-run]
description = "Run Slack bot container locally"
depends = ["slackbot-build"]
run = "docker run --env-file .env -it slackbot"

[tasks.slackbot-publish]
description = "Publish Slack bot container to registry"
depends = ["slackbot-build"]
run = """
docker tag slackbot $TF_VAR_region-docker.pkg.dev/$TF_VAR_project_id/catbot/slackbot:latest
docker push $TF_VAR_region-docker.pkg.dev/$TF_VAR_project_id/catbot/slackbot:latest
"""

[tasks.slackbot-publish-version]
description = "Publish Slack bot container with version tag"
depends = ["slackbot-build"]
run = """
docker tag slackbot $TF_VAR_region-docker.pkg.dev/$TF_VAR_project_id/catbot/slackbot:$VERSION
docker push $TF_VAR_region-docker.pkg.dev/$TF_VAR_project_id/catbot/slackbot:$VERSION
"""
